### ISSUE TITLE
Emplace method of definition container not forwarding arguments correctly

### ISSUE THREAD

**Issue by phijor** [tud-zih-energy/otf2xx#10]
In the signature of `otf2::definition::container::emplace` (see [here](https://github.com/tud-zih-energy/otf2xx/blob/ef2b9a7828ccb0204e450fb49dab6bdf58f38841/include/otf2xx/definition/container.hpp#L145)), should't `args` be of type `Args&&...` to enable perfect forwarding?

If so, I think `args` should be forwarded like so
```cpp
    std::forward_as_tuple(ref, std::forward<Args>(args)...)
```
when passing `args` to `emplace` of the underlying map ([here](https://github.com/tud-zih-energy/otf2xx/blob/ef2b9a7828ccb0204e450fb49dab6bdf58f38841/include/otf2xx/definition/container.hpp#L149)).

**Comment by bmario** [comment]
`Args&&...` seems like a good idea, but I'm not convinced that the forward is required. If you look at [cppreference](http://en.cppreference.com/w/cpp/utility/tuple/forward_as_tuple) it says that the return value of `forward_as_tuple` is:

```
std::tuple<Types&&...>(std::forward<Types>(args)...)
```

So there is already a forward.

**Comment by Flamefire** [comment]
@phijor is correct: https://godbolt.org/g/NPMueV

(expected) Errors:

> /opt/compiler-explorer/gcc-8.1.0/include/c++/8.1.0/tuple:1668:70: error: no matching function for call to 'std::__cxx11::basic_string<char>::basic_string(int&, const char*&)'

vs

> /opt/compiler-explorer/gcc-8.1.0/include/c++/8.1.0/tuple:1668:70: error: no matching function for call to 'std::__cxx11::basic_string<char>::basic_string(int&, const char*)'
