### ISSUE TITLE
Removing the start_time from all events time is unwanted

### ISSUE THREAD

**Issue by Flamefire** [tud-zih-energy/otf2xx#29]
First: [The docu of `start_time`](https://github.com/tud-zih-energy/otf2xx/blob/c63a2648abd82152b14a59b3ec771b423610c460/include/otf2xx/definition/clock_properties.hpp#L94) is wrong. The `start_time` and `length` are not related to the first and last timestamp in the trace. They just specify a period enclosing all timestamps which may not be the same.

But the problem is: All events reported by otf2xx [remove the start_time](https://github.com/tud-zih-energy/otf2xx/blob/ef2b9a7828ccb0204e450fb49dab6bdf58f38841/src/reader/callback/events.cpp#L70-L73). This is not documented and might break users code, especially as the conversion is not loss-less.

One example where this might be useful is when using timestamps based on real time. In that case this information is meaningful and should not be removed. I'd suggest keeping the ticks in the events and have the user convert them as required. This avoids overhead (by the conversion) and keeps the lossy conversion explicit.

**Comment by bmario** [comment]
You can still get this "lost" information from the clock_properties definition.

**Comment by Flamefire** [comment]
But not the lost precision and the runtime lost for conversion.

Furthermore the data gets inconsistent and wrong

- `start_time` is no longer less than every timestamp (in fact it is mostly larger)
- streaming data from one OTF2 trace to another modifies it:
  - timestamps get modified
  - `start_time` in the resulting trace would need to be adjusted but is not done
  - OR: timestamps need to have the `start_time` added again, but then still values are modified due to lost precision
