### ISSUE TITLE
Namespace does not match folder name

### ISSUE THREAD

**Issue by Flamefire** [tud-zih-energy/otf2xx#31]
It is common convention to have the namespace match the include folder name (see boost and pretty much every other project)
However for otf2xx the namespace is `otf2::` but the include folder is otf2xx. Either one should be renamed.

Renaming the folder would mean (potentially) putting the otf2xx files into the official otf2 folder, so unless this is meant to get official (which I'd support) I'd rename the namespace. Note that the folder rename would work, as all files are named `*.hpp` as opposed to `*.h` from the C interface.

Note: While this is a breaking API change either way, it is a very simple Search&Replace on either `otf2xx/` or `otf2::`, so trivial.

**Comment by tilsche** [comment]
This is a five year old project, we are not going to revisit every minor design decision - especially if it breaks the API.

**Comment by Flamefire** [comment]
"every minor design decision", really? I wouldn't call this minor and it is just a single thing. And I don't know how the age would be relevant.

Are there other projects **not** following this convention? Breaking expectations is almost always bad and should be avoided.

> especially if it breaks the API

Who is using this anyway? Most likely only your group and with fixed submodules. So the impact is low. As written an upgrade is exceptionally easy and one could even define a namespace alias.
