### ISSUE TITLE
io_pre_created_handle_states does not belong to registry

### ISSUE THREAD

**Issue by Flamefire** [tud-zih-energy/otf2xx#35]
Defined here: https://github.com/tud-zih-energy/otf2xx/blob/6ac2a9b42d279182df94fd8984e09f5b91444a0f/include/otf2xx/registry.hpp#L605

This definition is like a property. There is no reference to it.

Note: Things like that would be easier to catch when using more generic methods and explicitly defining the properties of definitions like "id space" with no specialization when they don't have one. See e.g. #32, #34. It would also be solved by using `otf2-template`, see #33

**Comment by bmario** [comment]
Fixed in b5f1761c3dbcdc1c439454a2e3fe51816a42ffd0
