### ISSUE TITLE
Move enums into otf2 namespace

### ISSUE THREAD

**Issue by Flamefire** [tud-zih-energy/otf2xx#41]
I found that using the enums from client code takes a lot of typing. Instead of `OTF2_LOCATION_TYPE_CPU_THREAD` you have `otf2::common::location_type::cpu_thread`.

Is there any benefit in the common namespace? The enums are already properly scoped and definitions and events have their own as well so moving them up should be fine. For the transition one could issue a simple `using namespace common` in the `otf2` namespace so it does not break the interface.

**Comment by bmario** [comment]
Why not 🤷‍♂️ We should check for conflicts though.
