### ISSUE TITLE
Lookup for registry

### ISSUE THREAD

**Issue by Flamefire** [tud-zih-energy/otf2xx#43]
The registry needs a way to lookup values in a way that is user-configurable. One could do this in a separate class but that means that every definition needs to be added to the registry and additionally to the other class. And `getOrCreate` is not possible at all.

For our project I create such a registry: https://gist.github.com/Flamefire/91211fdde109616e16ff8ea4a73baf24

Ideas used:
- List of all definitions exists (should be provided by otf2xx, can add after #40)
- Create 1 tuple containing all definition(holder)s
- `operator()` for adding any existing definition (1 function only!)
- `create<Definition>` function for creating and adding one
- `lookup<Definition>` function to get a definition from its key or definition
- `getOrCreate<Definition>` combine lookup and create. Mostly when the key can be converted to the definition but can also take a definition directly. This is basically what the python interface does: Create a definition, check if its key exists and return the existing or add the new one.
- `Registry` is templated on a key generator (default: key for string-defs is the string) as one cannot generically generate a key from a definition. Example: For my project regions with the same name are the same -> key=region.name. But for others they may want to check srcFile, lineNumbers...
- The key generator is a functor, taking a definition and returning a key. Only requirement for the key: Has to be usable in a map (std::less-comparable, copyable)
- The functor may return different keys based on the definition (allows e.g. zipping multiple values together in a tuple)

Notes:
- Providing writable access to the definition-holders is forbidden as it breaks the lookup
- read-only access is possible with `getAll<Definition>()` (only slightly longer than `Definitions()` and does not require endless copy&pasted code)
- from user code the accesses are more verbose (`create<otf2::definition::string>("foo")` vs `strings().create("foo")`) but when used with `using namespace otf2::definition` they are the same (`create<string>("foo")`)
- `operator[]` is missing for getting a definition from a reference. It is easy except for `definition!=tag` (like metric_class). Maybe you are right and we should keep `reference_impl<Def, Tag>` or we would need something like `get<metric_class>(metricRef)`
- One can completely disable the lookups by passing `void` or an empty class to as `GetKey` to `Registry`

Example code:

 ```
 struct GetKey: DefaultRegistryGetKey
  {
    using DefaultRegistryGetKey::operator();
    decltype(auto) operator()(const otf2::definition::system_tree_node& def) const
    {
      return def.name().str();
    }
    decltype(auto) operator()(const otf2::definition::region& def) const
    {
      return def.name().str();
    }
  };
  Registry<GetKey> registry_;
      auto sysTreeNode = registry_.lookup<otf2::definition::system_tree_node>(nodeName);
    if(!sysTreeNode.is_valid())
    {
      sysTreeNode = registry_.create<otf2::definition::system_tree_node>(
        registry_.getOrCreate<otf2::definition::string>(nodeName),
        registry_.getOrCreate<otf2::definition::string>("class"),
        rootNode_
        );
    }

    auto group = registry_.create<otf2::definition::location_group>(
      registry_.getOrCreate<otf2::definition::string>(process),
      otf2::common::location_group_type::process,
      sysTreeNode
    );

    auto location = registry_.create<otf2::definition::location>(
      registry_.getOrCreate<otf2::definition::string>(workerType + workerIdx),
      group,
      otf2::common::location_type::cpu_thread
    );

    auto writer = std::ref(archive_(location));
```

IMO this is easy to use and maintain and suitable for all use cases. I would therefore replace the current registry with this one. Any objections? (Details can be discussed in the PR, but don't want to waste the time preparing it if this is not wanted)

**Comment by bmario** [comment]
I like the general idea of using templatized functions to get definitions, but this seems either overkill or not generic enough to me

- The GetKey functor doesn't allow me to define a totally different key. The only properties of a definition itself used as keys are the name() and ref() but:
- the only unique key for a definition within its properties is its ref (within the same reference space), so one should have something like `equal_range` or it might get spooky.

To give you an idea of what we are doing in lo2s (simplified):

- We have system_tree_nodes for each recorded process and for each cpu, so we would like to index some by cpuid and some by pid
- We have locations for each cpu, for each recorded thread and for each async metric, so we would like to index some by cpuid, some by tid and some by metric name
- We have metrics recorded per process, per thread, per cpu, per package, and per host, so we would like to index them accordingly.

The current solution to this is to have [many](https://github.com/tud-zih-energy/lo2s/blob/master/include/lo2s/trace/trace.hpp#L259) [different](https://github.com/tud-zih-energy/lo2s/blob/master/include/lo2s/trace/trace.hpp#L270) [maps](https://github.com/tud-zih-energy/lo2s/blob/master/include/lo2s/trace/trace.hpp#L291) providing the various lookups. Ideally, I'd only have one registry. As we know the different domains and keys used at compile time, it may work using tag types as template arguments. However, I'm not sure, if this can be done.

*edit: some pseudo code may look like:

```
Registry reg;

reg.lookup<ByPid, otf2::definition::system_tree_node>(my_pid);

reg.create<ByCPU, otf2::definition::location>(cpuid, ...);
```

**Comment by Flamefire** [comment]
It actually is generic enough for most. Let's distinguish the 2 use cases (for lookup):

- Look up a definition by its reference: This is always unique if properly used (e.g. everything is created via `registry.create`. For that the registry (will) provide an `operator[]` which is a shortcut to `getAll<Def>()[ref]`. No problem here with semantics
- Look up a definition by a key. In the general case the key would be the definition (data) itself. So 2 definitions with the same data are equivalent and one would expect the registry to return/add only a single instance of it. This is what python OTF2 does. However this only works well for strings, as you'd need to create a definition (data) to find it. **BUT** for a specific use case one might consider regions with the same name as equivalent enabling lookup by the name. You can do this by providing an `string operator()(region)` in `GetKey` that returns the regions name. For another use case you decide, that also the src file must match and the start line number, so you create `tuple<string, string, int> operator()(region)` instead. This works perfectly: The key is whatever you return by the functor for a specific definition.

To show how to do this for lo2s:

- return a tuple `<bool, int>` as the key (assuming you can determine what a system_tree_node refers to by the definition itself)
- return a tuple `<typeEnum, int, string>`
- not quite sure, what this means, but if you can create a key from the definition, it works the same.

Generally the basic concept is:
- A registry has 1 container per definition
- Creating a definition will auto-create ref-numbers and add it to the correct container
- Lookup by ref number (uniquely)
- Lookup by a custom key which needs to be creatable from the definition. Only 1 lookup table is possible per definition / 1 key type per definition.

So scoping has to be done in the key type. If more advanced scoping is required, you'd better off with multiple maps. Doing that generically is almost impossible, unless you want to (always) pass the key value with the definition when adding it. Then we can have 1 table per `<keytype, definitiontype>` pair.

**Comment by bmario** [comment]
> It actually is generic enough for most.

To claim "for most" is a bit of a stretch when the only existing programs using otf2xx which I'm aware of, don't need that or it isn't generic enough. And that is my whole point.

> return a tuple <bool, int> as the key (assuming you can determine what a system_tree_node refers to by the definition itself)

That assumption does not hold.

I think only having a fixed lookup by ref (which is the only unique lookup), "name" and definition (for supplement definitions) is more than enough. This key generator seems to be too complicated and yet not powerful enough.

**Comment by Flamefire** [comment]
> This key generator seems to be too complicated and yet not powerful enough.

It is powerful enough for use cases where you can define a mapping between a definition and a key. There is no restriction on what they key is, how it is derived or what type it is. It also incurs NO overhead at all, if you don't need lookup (for all AND for only some definitions).   
Also I don't know what you mean by "too complicated". It is a simple functor, it can't get less complicated. You could even do `template<class T> std::string operator()(const T& d){return d.name();}` if you want that as the fallback.

> I think only having a fixed lookup by ref[...], "name" and definition [...] is more than enough.

Not at all.
- Lookup by ref is indisputable, you always need that (especially internally)
- "name": Not all definitions have a name. And the name might not be unique enough. 2 regions with the same name but in different source files are not the same. Only the (library) user knows, if that is an issue.
- definition: You can't compare definitions ATM, so you'd need to implement this for all definitions to allow this. This also won't be a lookup but rather a linear search in the container

Furthermore this means adding a map for each definition and an entry in that for every definition added even if you never do any lookup.

> the only existing programs using otf2xx which I'm aware of, don't need that or it isn't generic enough. 

As mentioned we currently use exactly this in our project. Your trace merger could also make use of this (you'd want to merge regions from different traces right? Or system_tree_nodes etc. And as mentioned for regions the name might not be enough)

**Comment by bmario** [comment]
I believe this issue is addressed in the current implementation of the lookup_registry. See here for an example of how to use that:
https://github.com/tud-zih-energy/otf2xx/blob/master/tests/lookup_registry_test.cpp
