### ISSUE TITLE
otf2xx fails to compile if libotf2 is installed to a default path

### ISSUE THREAD

**Issue by phijor** [tud-zih-energy/otf2xx#45]
When compiling `otf2xx` on my system, CMake fails to link any objects and throws the following error message:
```
 c++: error: /usr/lib/libotf2.a;/usr/lib/libm.so: No such file or directory
```
I have bisected the issue and found that 41c530c57e212d9cc151de7f282287c68fe249d2 seems to be the commit that introduces the breakage for me. In an attempt to uncover why CMake would behave in such an obtuse way, I have gained the following insights:

1. There *are* systems that make string parsing even less fun than C++ does.
2. In `cmake/FindOTF2.cmake`, the variable `OTF2_LIBRARIES` ends up with a value of `/usr/lib/libotf2.a;/usr/lib/libm.so` (which is *exactly* that from the error message)

There is a note in `FindOTF2.cmake` that tells me that `libm` should be filtered using the option `NO_DEFAULT_PATH` to `find_library`. But in my case, `otf2-config --ldflags` returns a library search directory that **contains** `libm.so`, thus it ends up being found regardless of `NO_DEFAULT_PATH`. On my system then things go :boom: since the target property `IMPORTED_LOCATION` only accepts a single path; not a list of paths.

After a lot of pulling my hair I may have found a workaround, but I'd like some input on this first:

1. parse libraries to link
2. set property `IMPORTED_LOCATION` to `/path/to/libotf2.a`
2. set property `INTERFACE_LINK_LIBRARIES` to the list of library files that *does not* contain `/path/to/libotf2.a`.

([here be the scrolls of truth](https://cmake.org/pipermail/cmake/2011-March/043148.html) :thinking:)

**Comment by bmario** [comment]
That is funny. First of all, you must be very brave, if you install random software with the prefix /usr.
Secondly, I've just learned that Debian obviously chooses another path to install libm.so to. Should work now though.

**Comment by Flamefire** [comment]
This issue is NOT fixed! All that is fixed is that libm is not searched for.

The issue here is: `IMPORTED_LOCATION "${OTF2_LIBRARIES}"` does not work, if there are multiple libraries. Just use `INTERFACE_LINK_LIBRARIES` instead.

Also note that the comment changed in 91fc167 is wrong: `# We have to "filter" -lm, as g++ links it anyways. And then stuff explodes`, err what? That is not the reason at all. The reason is, that `libm` must not be linked statically because this actually breaks horribly during linking (it is simply disallowed).

Also the `NO_DEFAULT_PATH` should be removed now, as it may be required for some other libraries `otf2-config` may return.

**Comment by bmario** [comment]
> if there are multiple libraries

There aren't. 

> Also the NO_DEFAULT_PATH should be removed now, as it may be required for some other libraries otf2-config may return.

Or it break because you have one version installed into a default path but want to link against another lib. Plus, it doesn't in version 2.1.1.

**Comment by Flamefire** [comment]
> There aren't.

Then why all this complicated looping and filtering if you know this already? Just get your include and library path and do a `find_library(otf2)`

> Or it break because you have one version installed into a default path but want to link against another lib. 

The approach recommended by CMake is 2 calls to `find_library`, the first with `NO_DEFAULT_PATH` and the 2nd without. But well, see above
