### ISSUE TITLE
Make reference_generator::next not change state

### ISSUE THREAD

**Issue by Flamefire** [tud-zih-energy/otf2xx#46]
`reference_generator` has mainly 2 functions:

- `next()` : Return the next ID
- `register_...`: Register a given ID as used

But currently `next()` does also register the reference which IMO is a mistake. For example when you want to create a definition but don't keep it.

A more concrete use-case:

- In the Registry you create a new definition
- You then create the hash/key/... from it and check, if that definition is already contained in it
- Depending on that you return either the old one, or add the new one and return that.

**Comment by bmario** [comment]
Yes and no. Initially, I wrote something about issues when considering threads, but I don't even need to go that far. What happens, if `next()` is called multiple times, before a new definition is registered?

```
auto ref_gen;
auto def1 = Def{ref_gen.next(),  ...};
auto def2 = Def{ref_gen.next(), ...};
// any combination
ref_gen.register(def1);
ref_gen.register(def2);
// ... or
ref_gen.register(def2);
ref_gen.register(def1);
// or
ref_gen.register(def1);
// or
ref_gen.register(def2);
```

You have to retro-change the reference number of created definition objects, which possibly changes the result of the lookup and thus the decision to keep them in the first place. The only strategy, which allows you to maintain a consistent reference number space is to commit to the creation of a definition object, once next() was called, aka do the lookup beforehand.

Issues like this one are the reason why there hasn't been a registry in otf2xx for years.

**Comment by Flamefire** [comment]
IMO this is a hint of a design flaw.

Having multiple definitions with the same ID is per se OK. (There might be use cases for that)
If you are going to register them anyway: Why not call something like `create_and_register` (like in the registry)? Or use another function `next_and_register` on the raw generator.

About threads: Dosn't matter. None of the classes are thread-safe. It is the users responsibility to achieve that.

**Comment by bmario** [comment]
> Having multiple definitions with the same ID is per se OK. (There might be use cases for that)

Within one ID space, which is represented by one registry, it's not ok. It's invalid. A registry isn't a container of definitions; it's a container of definitions *of one trace*. Therefore, that would result in an invalid trace file. Additionally, that doesn't work in the python bindings either.

> If you are going to register them anyway: Why not call something like `create_and_register` (like in the registry)? Or use another function `next_and_register` on the raw generator.

I can rename the methods, but that wouldn't magically let the issue disappear.

**Comment by Flamefire** [comment]
>Within one ID space, which is represented by one registry, it's not ok. It's invalid. A registry isn't a container of definitions; it's a container of definitions of one trace. Therefore, that would result in an invalid trace file. Additionally, that doesn't work in the python bindings either.

If you have a registry you should hence create the definitions in the registry too which does the registering. (That's what I meant)

> I can rename the methods, but that wouldn't magically let the issue disappear.

Point was to have both. See the use case described

**Comment by bmario** [comment]
a8f55ad670daad4f3195ea02e4c2965718bd12d6 added `peak()`. This still isn't a good idea...
