### ISSUE TITLE
otf2::chrono::time_points can be negative while OTF2_TimeStamp is unsigned

### ISSUE THREAD

**Issue by cvonelm** [tud-zih-energy/otf2xx#48]
I've discovered this bug while using otf2::chrono::genesis(), which returns the smallest possible std::chrono::time_point which is a large negative number, which when written as an event's time_point will be converted to a large positive number

This is roughly the situation where i encountered this bug:
```cpp
otf2::chrono::time_point past = otf2::chrono::genesis() // -9223372036854775808 on my system
otf2::chrono::time_point now = now() 
writer.write_calling_context_enter(past)
writer.write_calling_context_leave(now) // error: Parameter value out of range: Passed timestamp is smaller than last written one! (29778508888465 < 9223372036854775808)

```

**Comment by bmario** [comment]
I'm not sure if I'd call that a bug. Technically speaking `otf2::chrono::time_point`s aren't the equivalent of `OTF2_TimeStamp`s. That is what `otf2::chrono::ticks` is for. I admit, the behavior is a bit surprising and the error a bit confusing, but I'm not sure if I'm willing to pay for the same check twice.

Solution: Don't use `otf2::chrono::genesis()` to initialize time_points where this value may actually be written to the trace. Use the default constructor then, i.e. duration(0).
