### ISSUE TITLE
Required OTF2 version

### ISSUE THREAD

**Issue by NanoNabla** [tud-zih-energy/otf2xx#67]
In [CMakeLists.txt](https://github.com/tud-zih-energy/otf2xx/blob/84b2f5b1fc9c0b09e98ee51af7c25f01b8df2665/CMakeLists.txt#L37) you require OTF2 9.0.2 and do not allow newer versions like 9.1.2

Are there any known issues with other (newer) OTF2 versions or could I just use it with 9.1.2?

**Comment by bmario** [comment]
Since otf2xx mainly depends on API compatibility, I guess it should be fine. Though, to my knowledge, nobody tried it yet.
